"""initial sqlite schema

Revision ID: 9dbeeab677e0
Revises:
Create Date: 2026-03-14 11:57:29.437255

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dbeeab677e0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phone_number", sa.Text(), nullable=False),
        sa.Column("telegram_user_id", sa.BIGINT(), nullable=True),
        sa.Column("session_string", sa.Text(), nullable=True),
        sa.Column("temp_session_string", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("llm_consent_given", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_phone_number"), ["phone_number"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_telegram_user_id"), ["telegram_user_id"], unique=True
        )

    op.create_table(
        "insights",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chat_ids", sa.JSON(), nullable=False),
        sa.Column("chat_titles", sa.JSON(), nullable=True),
        sa.Column("start_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("model_used", sa.Text(), nullable=False),
        sa.Column("provider_used", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.DECIMAL(precision=10, scale=6), nullable=True),
        sa.Column("generation_time_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("insights", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insights_user_id"), ["user_id"], unique=False)

    op.create_table(
        "message_fetches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("messages_count", sa.Integer(), nullable=False),
        sa.Column("total_channels", sa.Integer(), nullable=True),
        sa.Column("completed_channels", sa.Integer(), nullable=False),
        sa.Column("current_channel_title", sa.String(length=255), nullable=True),
        sa.Column("failed_channels", sa.JSON(), nullable=True),
        sa.Column("channel_ids", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=30), nullable=True),
        sa.Column("current_phase", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message_fetches", schema=None) as batch_op:
        batch_op.create_index("idx_fetches_user_started", ["user_id", "started_at"], unique=False)

    op.create_table(
        "user_channel_favorites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.BIGINT(), nullable=False),
        sa.Column("channel_title", sa.String(length=255), nullable=True),
        sa.Column("channel_type", sa.String(length=50), nullable=True),
        sa.Column("favorited_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "channel_id", name="uq_user_channel_favorite"),
    )
    with op.batch_alter_table("user_channel_favorites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_channel_favorites_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_channel_selections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.BIGINT(), nullable=False),
        sa.Column("channel_title", sa.String(length=255), nullable=True),
        sa.Column("channel_type", sa.String(length=50), nullable=True),
        sa.Column("selected_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "channel_id", name="uq_user_channel_selection"),
    )
    with op.batch_alter_table("user_channel_selections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_channel_selections_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_insights_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_insights_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_insights_usage_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("telegram_message_id", sa.BIGINT(), nullable=False),
        sa.Column("chat_id", sa.BIGINT(), nullable=False),
        sa.Column("chat_title", sa.String(length=255), nullable=True),
        sa.Column("chat_type", sa.String(length=20), nullable=False),
        sa.Column("sender_id", sa.BIGINT(), nullable=True),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("message_type", sa.String(length=20), nullable=False),
        sa.Column("has_media", sa.Boolean(), nullable=False),
        sa.Column("file_id", sa.BIGINT(), nullable=True),
        sa.Column("file_name", sa.String(length=500), nullable=True),
        sa.Column("file_mime_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.BIGINT(), nullable=True),
        sa.Column("file_duration", sa.Integer(), nullable=True),
        sa.Column("file_width", sa.Integer(), nullable=True),
        sa.Column("file_height", sa.Integer(), nullable=True),
        sa.Column("is_reply", sa.Boolean(), nullable=False),
        sa.Column("is_forward", sa.Boolean(), nullable=False),
        sa.Column("additional_metadata", sa.JSON(), nullable=True),
        sa.Column("fetch_id", sa.Uuid(), nullable=True),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fetch_id"], ["message_fetches.id"], name="fk_messages_fetch_id", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index("idx_messages_media", ["user_id", "has_media"], unique=False)
        batch_op.create_index(
            "idx_messages_user_chat_time", ["user_id", "chat_id", "timestamp"], unique=False
        )
        batch_op.create_index("idx_messages_user_time", ["user_id", "timestamp"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_fetch_id"), ["fetch_id"], unique=False)

    # FTS5 virtual table and triggers for full-text search on message content
    op.execute(
        "CREATE VIRTUAL TABLE messages_fts USING fts5("
        "content, content_rowid='id', tokenize='unicode61')"
    )
    op.execute(
        "CREATE TRIGGER messages_ai AFTER INSERT ON messages BEGIN "
        "INSERT INTO messages_fts(rowid, content) VALUES (new.id, new.content); "
        "END"
    )
    op.execute(
        "CREATE TRIGGER messages_au AFTER UPDATE ON messages BEGIN "
        "UPDATE messages_fts SET content = new.content WHERE rowid = old.id; "
        "END"
    )
    op.execute(
        "CREATE TRIGGER messages_ad AFTER DELETE ON messages BEGIN "
        "DELETE FROM messages_fts WHERE rowid = old.id; "
        "END"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_fetch_id"))
        batch_op.drop_index("idx_messages_user_time")
        batch_op.drop_index("idx_messages_user_chat_time")
        batch_op.drop_index("idx_messages_media")

    op.drop_table("messages")
    with op.batch_alter_table("user_insights_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_insights_usage_user_id"))

    op.drop_table("user_insights_usage")
    with op.batch_alter_table("user_channel_selections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_channel_selections_user_id"))

    op.drop_table("user_channel_selections")
    with op.batch_alter_table("user_channel_favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_channel_favorites_user_id"))

    op.drop_table("user_channel_favorites")
    with op.batch_alter_table("message_fetches", schema=None) as batch_op:
        batch_op.drop_index("idx_fetches_user_started")

    op.drop_table("message_fetches")
    with op.batch_alter_table("insights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insights_user_id"))

    op.drop_table("insights")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_telegram_user_id"))
        batch_op.drop_index(batch_op.f("ix_users_phone_number"))

    op.drop_table("users")
    # ### end Alembic commands ###
